/**
 * Cloud Functions: Send auth emails (verification + password reset) via Resend.
 * This sends from YOUR domain (e.g. noreply@tawfirenergy.com) with proper
 * SPF/DKIM, so emails are much less likely to go to spam.
 *
 * Setup: see EMAIL_DELIVERABILITY_GUIDE.md and create functions/.env with
 * RESEND_API_KEY, RESEND_FROM_EMAIL, optional RESEND_FROM_NAME.
 *
 * Continue URLs after verify/reset must be static HTML under Firebase Hosting
 * (see web/email-verified.html, web/password-reset-complete.html), NOT the SPA
 * root — otherwise users land on the admin web login. Keep URLs aligned with
 * lib/core/constants/auth_email_continue_urls.dart.
 */

import { onCall, HttpsError } from "firebase-functions/v2/https";
import { defineString } from "firebase-functions/params";
import { getAuth } from "firebase-admin/auth";
import { getApps, initializeApp } from "firebase-admin/app";
import { Resend } from "resend";

const resendApiKey = defineString("RESEND_API_KEY", { description: "Resend API key" });
const resendFromEmail = defineString("RESEND_FROM_EMAIL", { description: "From email e.g. noreply@yourdomain.com" });
const resendFromName = defineString("RESEND_FROM_NAME", { default: "Tawfir Energy" });

if (!getApps().length) {
  initializeApp();
}

const auth = getAuth();

/** Firebase Auth redirect after email action (must be hosted + authorized domain). */
const EMAIL_VERIFIED_CONTINUE_URL =
  "https://solar-app-f698e.firebaseapp.com/email-verified.html";
const PASSWORD_RESET_CONTINUE_URL =
  "https://solar-app-f698e.firebaseapp.com/password-reset-complete.html";

function getResendConfig() {
  const apiKey = resendApiKey.value();
  const fromEmail = resendFromEmail.value();
  const fromName = resendFromName.value();
  if (!apiKey || !fromEmail) {
    throw new HttpsError(
      "failed-precondition",
      "Missing Resend config. Add RESEND_API_KEY and RESEND_FROM_EMAIL to functions/.env (see EMAIL_DELIVERABILITY_GUIDE.md)."
    );
  }
  const fromDisplay = fromName ? `${fromName} <${fromEmail}>` : fromEmail;
  return { apiKey, fromEmail: fromDisplay, fromEmailRaw: fromEmail };
}

/**
 * Callable: Send email verification using a link generated by Firebase Admin,
 * then send the email via Resend (your domain). Call this after sign-up instead
 * of user.sendEmailVerification() to avoid spam.
 */
export const sendAuthVerificationEmail = onCall(
  { enforceAppCheck: false },
  async (request) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "Must be signed in to request verification email.");
    }
    const email = request.auth.token.email;
    if (!email) {
      throw new HttpsError("invalid-argument", "No email on account.");
    }

    const { apiKey, fromEmail, fromEmailRaw } = getResendConfig();
    const resend = new Resend(apiKey);

    let link;
    try {
      // handleCodeInApp: true caused continueUrl to become the bare hosting origin only
      // (…/?continueUrl=https%3A%2F%2Fproject.firebaseapp.com), which loads the SPA/admin.
      // false keeps url=…/email-verified.html intact so Firebase sends users there after Continue.
      link = await auth.generateEmailVerificationLink(email, {
        url: EMAIL_VERIFIED_CONTINUE_URL,
        handleCodeInApp: false,
      });
    } catch (e) {
      console.error("generateEmailVerificationLink failed", e);
      throw new HttpsError("internal", "Could not generate verification link.");
    }

    const subject = "Verify your email – Tawfir Energy";
    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#333;">
  <h2 style="color:#1a1a1a;">Verify your email</h2>
  <p>Thanks for signing up for Tawfir Energy. Please confirm your email address by clicking the button below.</p>
  <p style="margin:28px 0;">
    <a href="${link}" style="display:inline-block;background:#0d6efd;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;">Verify email</a>
  </p>
  <p style="font-size:14px;color:#666;">If you didn't create an account, you can ignore this email.</p>
  <p style="font-size:14px;color:#666;">— Tawfir Energy</p>
</body>
</html>`;
    const text = `Verify your email – Tawfir Energy\n\nThanks for signing up for Tawfir Energy. Please confirm your email by opening this link:\n\n${link}\n\nIf you didn't create an account, you can ignore this email.\n\n— Tawfir Energy`;

    const { data, error } = await resend.emails.send({
      from: fromEmail,
      to: [email],
      reply_to: fromEmailRaw,
      subject,
      html,
      text,
      headers: { "X-Entity-Ref-ID": `verify-${Date.now()}-${email}` },
    });

    if (error) {
      console.error("Resend send failed", error);
      throw new HttpsError("internal", "Failed to send verification email. Try again later.");
    }
    return { ok: true, id: data?.id };
  }
);

/**
 * Callable: Send password reset email using a link generated by Firebase Admin,
 * then send the email via Resend (your domain). Call this from "Forgot password"
 * instead of Firebase Auth sendPasswordResetEmail() to avoid spam.
 */
export const sendAuthPasswordResetEmail = onCall(
  { enforceAppCheck: false },
  async (request) => {
    const email = request.data?.email;
    if (!email || typeof email !== "string" || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
      throw new HttpsError("invalid-argument", "Valid email is required.");
    }
    const trimmedEmail = email.trim();

    const { apiKey, fromEmail, fromEmailRaw } = getResendConfig();
    const resend = new Resend(apiKey);

    let link;
    try {
      link = await auth.generatePasswordResetLink(trimmedEmail, {
        url: PASSWORD_RESET_CONTINUE_URL,
        handleCodeInApp: false,
      });
    } catch (e) {
      // Don't reveal whether the email exists; still return success for security
      if (e.code === "auth/user-not-found") {
        return { ok: true };
      }
      console.error("generatePasswordResetLink failed", e);
      throw new HttpsError("internal", "Could not send reset email. Try again later.");
    }

    const subject = "Reset your password – Tawfir Energy";
    const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#333;">
  <h2 style="color:#1a1a1a;">Reset your password</h2>
  <p>You requested a password reset for your Tawfir Energy account. Click the button below to set a new password.</p>
  <p style="margin:28px 0;">
    <a href="${link}" style="display:inline-block;background:#0d6efd;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;">Reset password</a>
  </p>
  <p style="font-size:14px;color:#666;">If you didn't request this, you can ignore this email. Your password will not change.</p>
  <p style="font-size:14px;color:#666;">— Tawfir Energy</p>
</body>
</html>`;
    const text = `Reset your password – Tawfir Energy\n\nYou requested a password reset. Open this link to set a new password:\n\n${link}\n\nIf you didn't request this, ignore this email. Your password will not change.\n\n— Tawfir Energy`;

    const { data, error } = await resend.emails.send({
      from: fromEmail,
      to: [trimmedEmail],
      reply_to: fromEmailRaw,
      subject,
      html,
      text,
      headers: { "X-Entity-Ref-ID": `reset-${Date.now()}-${trimmedEmail}` },
    });

    if (error) {
      console.error("Resend send failed", error);
      throw new HttpsError("internal", "Failed to send reset email. Try again later.");
    }
    return { ok: true, id: data?.id };
  }
);
